name: Daily Weather Report

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust timezone as needed)
    # Use https://crontab.guru/ to help with cron expressions
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-weather-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run weather report
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CITY: ${{ secrets.CITY }}
      run: |
        python main.py
    
    - name: Log completion
      run: |
        echo "Weather report sent at $(date)"
