name: Daily Weather Reports

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch:  # Allows manual triggering
    inputs:
      report_type:
        description: 'Type of report to run'
        required: true
        default: 'auto'
        type: choice
        options:
        - auto
        - morning
        - evening

jobs:
  send-weather-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Determine report type
      id: report_type
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "type=${{ github.event.inputs.report_type }}" >> $GITHUB_OUTPUT
        else
          # When using auto mode, the script will determine based on user timezone
          echo "type=auto" >> $GITHUB_OUTPUT
        fi
    
    - name: Run weather report
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CITY: ${{ secrets.CITY }}
        WEATHER_PROVIDER: ${{ secrets.WEATHER_PROVIDER }}
        USER_TIMEZONE: ${{ secrets.USER_TIMEZONE }}
        REPORT_TYPE: ${{ steps.report_type.outputs.type }}
      run: |
        echo "Running ${{ steps.report_type.outputs.type }} report..."
        echo "Weather provider: ${WEATHER_PROVIDER:-openweathermap}"
        echo "User timezone: ${USER_TIMEZONE:-UTC}"
        python main.py
    
    - name: Commit and push data files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add temp_readings.json morning_forecast.json 2>/dev/null || true
        git diff --staged --quiet || git commit -m "Update weather data files - ${{ steps.report_type.outputs.type }} report"
        git push || echo "No changes to push"
    
    - name: Log completion
      run: |
        echo "${{ steps.report_type.outputs.type }} weather report sent at $(date)"
